### ISSUE TITLE
curseradio can't retrieve opml file due to lxml no_network policy

### ISSUE THREAD

**Issue by emulti** [chronitis/curseradio#22]
When running curseradio (tested on Arch Linux and OpenBSD) the program crashes with:

OSError: Error reading file 'http://opml.radiotime.com/': failed to load "http://opml.radiotime.com/": Attempt to load network entity

This seems to be due to lxml now having a no_network policy unless overridden.  I tried to work out how to change this in such a wy that only the specific opml URL is permitted, but didn't succeed. Any ideas?

```
$ curseradio 
Traceback (most recent call last):
  File "/usr/bin/curseradio", line 33, in <module>
    sys.exit(load_entry_point('curseradio==0.2', 'console_scripts', 'curseradio')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/curseradio/__main__.py", line 5, in main
    curses.wrapper(OPMLBrowser)
  File "/usr/lib/python3.12/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/curseradio/curseradio.py", line 266, in __init__
    self.root = OPMLOutline.from_xml(self.config['opml']['root'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/curseradio/curseradio.py", line 62, in from_xml
    tree = lxml.etree.parse(url)
           ^^^^^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 3589, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1958, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1984, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1887, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1200, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 633, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 743, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 670, in lxml.etree._raiseParseError
OSError: Error reading file 'http://opml.radiotime.com/': failed to load "http://opml.radiotime.com/": Attempt to load network entity

```

**Comment by elewarr** [comment]
@emulti, please check this PR: https://github.com/chronitis/curseradio/pull/17.

**Comment by emulti** [comment]
Thanks- I modified the PKGBUILD for Arch to pull from the 'elewarr' GH account and added a note there for the maintainer
Will you be updating the OpenBSD port, as I see you are listed as the Maintainer?
Chris

**Comment by elewarr** [comment]
Yes, I'm going to do the same - switch completely to my GH fork, for OpenBSD curseradio port.
