### ISSUE TITLE
Was working fine. Added Favorites, now won't load

### ISSUE THREAD

**Issue by TanukiKabuki** [chronitis/curseradio#8]
This is what I get after issuing a terminal command to load it.

> Traceback (most recent call last):
  File "/usr/bin/curseradio", line 6, in <module>
    curses.wrapper(lambda s: OPMLBrowser(s, ROOT))
  File "/usr/lib/python3.5/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/bin/curseradio", line 6, in <lambda>
    curses.wrapper(lambda s: OPMLBrowser(s, ROOT))
  File "/usr/lib/python3.5/dist-packages/curseradio/curseradio.py", line 245, in __init__
    self.favourites = self.load_favourites()
  File "/usr/lib/python3.5/dist-packages/curseradio/curseradio.py", line 263, in load_favourites
    return OPMLFavourites.from_xml(str(opmlpath))
  File "/usr/lib/python3.5/dist-packages/curseradio/curseradio.py", line 44, in from_xml
    for o in tree.xpath('/opml/body/outline')]
  File "/usr/lib/python3.5/dist-packages/curseradio/curseradio.py", line 44, in <listcomp>
    for o in tree.xpath('/opml/body/outline')]
  File "/usr/lib/python3.5/dist-packages/curseradio/curseradio.py", line 69, in from_element
    assert len(element) == 0
AssertionError

**Comment by DarkNemesis200** [comment]
I'm not sure exactly what causes this but if you remove $HOME/.local/curseradio/favourites.opml it will work as a quick fix.
